// Building
export const CLICK_ON_BUILDING = 'CLICK_ON_BUILDING';
export const RETURN_TO_HOME_CLICKED = 'RETURN_TO_HOME_CLICKED';

// Map
export const MAP_BOUNDS_CHANGED = 'MAP_BOUNDS_CHANGED';
export const MAP_PROJECTION_CHANGED = 'MAP_PROJECTION_CHANGED';

// Geolocation autocomplete
export const CLICK_ON_SUGGESTED_ADDRESS = 'CLICK_ON_SUGGESTED_ADDRESS';
