name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test --passWithNoTests
      - name: Build 🔧
        run: yarn build
