name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn install --immutable
      - name: Test
        run: yarn test
      - name: Build 🔧
        run: yarn build
